// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Queries$HasuraReasonDemoApp from "../queries/Queries.js";

function AddPostForm(Props) {
  var closeModal = Props.closeModal;
  var match = React.useState((function () {
          return "";
        }));
  var setTitle = match[1];
  var title = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setContent = match$1[1];
  var content = match$1[0];
  var match$2 = React.useState((function () {
          return false;
        }));
  var setSanitize = match$2[1];
  var sanitize = match$2[0];
  var match$3 = React.useState((function () {
          return "https://images.unsplash.com/photo-1555397430-57791c75748a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80";
        }));
  var setCoverImage = match$3[1];
  var coverImg = match$3[0];
  return React.createElement(Queries$HasuraReasonDemoApp.AddPostMutation[/* make */6], {
              children: (function (mutation, param) {
                  var addNewPostMutation = Queries$HasuraReasonDemoApp.PostMutation[/* make */3](title, content, sanitize, coverImg, /* () */0);
                  var addNewPost = function (param) {
                    Curry._1(closeModal, /* () */0);
                    Curry._4(mutation, Caml_option.some(addNewPostMutation.variables), undefined, undefined, /* () */0);
                    return /* () */0;
                  };
                  return React.createElement("form", {
                              className: "w-full",
                              onSubmit: (function ($$event) {
                                  $$event.preventDefault();
                                  return addNewPost(/* () */0);
                                })
                            }, React.createElement("div", {
                                  className: "md:flex md:items-center mb-6"
                                }, React.createElement("div", {
                                      className: "md:w-1/12"
                                    }, React.createElement("label", {
                                          className: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4",
                                          htmlFor: "inline-full-name"
                                        }, "Title")), React.createElement("div", {
                                      className: "md:w-11/12"
                                    }, React.createElement("input", {
                                          className: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500",
                                          id: "inline-full-name",
                                          placeholder: "Enter your title",
                                          type: "text",
                                          value: title,
                                          onChange: (function (e) {
                                              return Curry._1(setTitle, e.target.value);
                                            })
                                        }))), React.createElement("div", {
                                  className: "md:flex md:items-center mb-6"
                                }, React.createElement("div", {
                                      className: "md:w-1/12"
                                    }, React.createElement("label", {
                                          className: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4",
                                          htmlFor: "inline-image"
                                        }, "Cover image url")), React.createElement("div", {
                                      className: "md:w-11/12"
                                    }, React.createElement("input", {
                                          className: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500",
                                          id: "inline-image",
                                          type: "text",
                                          value: coverImg,
                                          onChange: (function (e) {
                                              return Curry._1(setCoverImage, e.target.value);
                                            })
                                        }))), React.createElement("div", {
                                  className: "md:flex md:items-center mb-6"
                                }, React.createElement("div", {
                                      className: "md:w-1/12"
                                    }, React.createElement("label", {
                                          className: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4",
                                          htmlFor: "inline-username"
                                        }, "Content")), React.createElement("div", {
                                      className: "md:w-11/12"
                                    }, React.createElement("textarea", {
                                          className: "h-20 bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500",
                                          id: "inline-username",
                                          placeholder: "Write your post content",
                                          type: "text",
                                          value: content,
                                          onChange: (function (e) {
                                              return Curry._1(setContent, e.target.value);
                                            })
                                        }))), React.createElement("div", {
                                  className: "md:flex md:items-center mb-6"
                                }, React.createElement("div", {
                                      className: "md:w-1/12"
                                    }), React.createElement("label", {
                                      className: "md:w-11/12 block text-gray-500 font-bold"
                                    }, React.createElement("input", {
                                          className: "mr-2 leading-tight",
                                          checked: sanitize,
                                          type: "checkbox",
                                          onChange: (function (e) {
                                              return Curry._1(setSanitize, e.target.checked);
                                            })
                                        }), React.createElement("span", {
                                          className: "text-sm"
                                        }, "Check bad words"))), React.createElement("div", {
                                  className: "md:flex md:items-center"
                                }, React.createElement("div", {
                                      className: "md:w-1/12"
                                    }), React.createElement("div", {
                                      className: "md:w-11/12"
                                    }, React.createElement("button", {
                                          className: "shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded",
                                          type: "button",
                                          onClick: (function (param) {
                                              return addNewPost(/* () */0);
                                            })
                                        }, "Submit"))));
                })
            });
}

var make = AddPostForm;

export {
  make ,
  
}
/* react Not a pure module */
