// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Post$HasuraReasonDemoApp from "./Post.js";
import * as Queries$HasuraReasonDemoApp from "../queries/Queries.js";

function PostsList(Props) {
  return React.createElement("div", {
              className: "flex flex-wrap"
            }, React.createElement(Queries$HasuraReasonDemoApp.GetPostsQuery[/* make */4], {
                  children: (function (param) {
                      var result = param[/* result */0];
                      if (typeof result === "number") {
                        return "Loading";
                      } else if (result.tag) {
                        var posts = result[0].posts;
                        return $$Array.map((function (post) {
                                      return React.createElement("div", {
                                                  className: "bg-white rounded-t-lg overflow-hidden p-4 p-10 flex justify-center"
                                                }, React.createElement(Post$HasuraReasonDemoApp.make, {
                                                      post: post
                                                    }));
                                    }), posts);
                      } else {
                        console.log(result[0]);
                        return "Error";
                      }
                    })
                }));
}

var make = PostsList;

export {
  make ,
  
}
/* react Not a pure module */
